import javax.persistence {
	embeddable,
	column__FIELD
}

"""
   Uniquely identifies a particular cargo. Automatically generated by the
   application.
""" 
embeddable
shared class VoyageNumber(number) {
	
	column__FIELD{name = "voyage_number";}
	shared String number;
	
	shared Boolean sameValueAs(VoyageNumber other) => this.number == other.number;
	
}