import javax.persistence {
	embeddable,
	column__FIELD
}

"""
   Uniquely identifies a particular cargo. Automatically generated by the
   application.
""" 
embeddable
shared class VoyageNumber {
	
	column__FIELD{name = "voyage_number";}
	shared String number;
	
	
	
	shared new init(String number){
		this.number = number;
	}
	
	shared new() extends init(""){}
	
	shared Boolean sameValueAs(VoyageNumber other) => this.number == other.number;
	
}